ktor:
    application:
        modules:
            - store.com.ApplicationKt.module
    deployment:
        port: 6001
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
